### PR TITLE
Force safer whitenoise versions >= 4.1.3

### PR DESCRIPTION
**Pull request by jmurty**
Version 4.1.3 is the first that safely handles
dangerous whitenoise configuration options that
if poorly set can expose arbitrary server files:

    WHITENOISE_AUTOREFRESH=True
    WHITENOISE_USE_FINDERS=True

### CODE REVIEW

**Comment by Aramgutang** [comment]
Is it really this package's job to set those requirements? It doesn't even set those settings to the dangerous values. The requirements should probably represent what it supports, not try to be a do-gooder.

**Comment by jmurty** [comment]
You make good points @Aramgutang but this is the only place I could find where we enforce any particular version of _whitenoise_.

Forcing the "right" or "best" version might be more the job of _ixc-django-docker_, though it arguably isn't even necessary to force a version if the dangerous settings aren't applied in the first place.

**Comment by Aramgutang** [comment]
And the dangerous settings are no longer applied in ixc-django-docker.

**Comment by jmurty** [comment]
Yep, but it's more likely for sites to be able to upgrade `ixc_whitenoise` than all of `ixc-django-docker`

**Comment by jmurty** [comment]
I'm withdrawing this PR since enforcing a later version of whitenoise here isn't the right way to solve this problem.

To avoid security problems, all `ixc-whitenoise` should do (if anything) is detect when a site is running with dangerous settings and log the problem, or fail to load the site if we're serious about it.

**Pull request closed without merging**
